### ISSUE TITLE
Scar is always rolled with d12

### ISSUE THREAD

**Issue by TeddyDD** [maqloner/mythic-bastionland-fvtt#10]
Selecting scar die does not have effect in „Roll Scar” dialog. It's always d12. 

I tried to debug this but I'm not well versed in JS. Looks like die is selected correctly from the dialog in `roll-scar-dialog.js` by the JQuery but something happens later in the callback, and it gets ignored.

**Comment by maqloner** [comment]
Fixed in 1.0.4
